sudo: true
language: ruby
rvm:
  - '2.3'
  - '2.4'
  - '2.5'
  - 'jruby-9.1.15.0'
matrix:
    allow_failures:
        - rvm: 'jruby-9.1.15.0'

install:
  - sudo apt-get install build-essential
  - gem install bundler
  - bundle install --path vendor/bundle

script:
  - bundle exec rake
  - bundle exec rake test
